services:
  # 第一个 Nacos 实例的配置
  nacos1:
    # 使用 Nacos 官方镜像版本 2.2.0
    image: nacos/nacos-server:v2.2.0
    # 容器名称为 nacos1，方便识别和管理
    container_name: nacos1
    # 确保容器的主机名为 nacos1（不可省略）
    hostname: nacos1
    environment:
      # 集群模式，Nacos 运行在集群模式下
      - MODE=cluster
      # 使用主机名进行节点间通信（不可省略）
      - PREFER_HOST_MODE=hostname
      # 定义集群中的 Nacos 节点地址，使用主机名
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
      #- NACOS_SERVER_IP=nacos1
      # 数据源平台为 MySQL
      - SPRING_DATASOURCE_PLATFORM=mysql
      # 指定 MySQL 服务主机名
      - MYSQL_SERVICE_HOST=mysql
      # Nacos 使用的 MySQL 数据库名称
      - MYSQL_SERVICE_DB_NAME=nacos
      # MySQL 数据库端口
      - MYSQL_SERVICE_PORT=3306
      # 连接 MySQL 数据库的用户名
      - MYSQL_SERVICE_USER=nacos
      # 连接 MySQL 数据库的密码
      - MYSQL_SERVICE_PASSWORD=123456
      # 设置 JVM 参数以最小化内存使用
      - JAVA_OPTS=-Xms256m -Xmx256m -Xmn128m
    volumes:
      # 将宿主机上的 application.properties 文件挂载到 Nacos 容器中
      - ./nacos/config/application.properties:/home/nacos/conf/application.properties
      # 集群配置
      - ./nacos/config/cluster.conf:/home/nacos/conf/cluster.conf
      # 将 Nacos 日志目录持久化到宿主机，确保日志不会因容器重启而丢失
      - ./nacos/logs/nacos1:/home/nacos/logs
      # 将 Nacos 数据目录持久化到宿主机，防止配置和服务注册信息丢失
      - ./nacos/data/nacos1:/home/nacos/data
    # 映射 Nacos 容器的 8848 端口到宿主机，允许外部访问
    ports:
      - "8848:8848"
      - "7848:7848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - nacos-network

  # 第二个 Nacos 实例的配置
  nacos2:
    image: nacos/nacos-server:v2.2.0
    container_name: nacos2
    hostname: nacos2
    environment:
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=123456
      - JAVA_OPTS=-Xms256m -Xmx256m -Xmn128m
    volumes:
      - ./nacos/config/application.properties:/home/nacos/conf/application.properties
      - ./nacos/config/cluster.conf:/home/nacos/conf/cluster.conf
      - ./nacos/logs/nacos2:/home/nacos/logs
      - ./nacos/data/nacos2:/home/nacos/data
    ports:
      - "8849:8848"
    networks:
      - nacos-network

  # 第三个 Nacos 实例的配置
  nacos3:
    image: nacos/nacos-server:v2.2.0
    container_name: nacos3
    hostname: nacos3
    environment:
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=123456
      - JAVA_OPTS=-Xms256m -Xmx256m -Xmn128m
    volumes:
      - ./nacos/config/application.properties:/home/nacos/conf/application.properties
      - ./nacos/config/cluster.conf:/home/nacos/conf/cluster.conf
      - ./nacos/logs/nacos3:/home/nacos/logs
      - ./nacos/data/nacos3:/home/nacos/data
    ports:
      - "8850:8848"
    networks:
      - nacos-network

  # MySQL 数据库服务的配置，Nacos 集群依赖 MySQL 数据库存储配置信息
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      # MySQL root 用户的密码
      - MYSQL_ROOT_PASSWORD=root
      # 创建 Nacos 所需的数据库
      - MYSQL_DATABASE=nacos
      # 创建数据库用户，用于连接 Nacos
      - MYSQL_USER=nacos
      # 连接数据库用户的密码
      - MYSQL_PASSWORD=123456
    volumes:
      # 持久化 MySQL 数据到宿主机，防止数据丢失
      - ./mysql:/var/lib/mysql
      # 自动加载 MySQL 初始化 SQL 脚本，用于创建 Nacos 数据表
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      # 映射 MySQL 容器的 3306 端口到宿主机，允许外部访问
      - "3307:3306"
    networks:
      - nacos-network

networks:
  nacos-network:
    external: true